name: Integration tests
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: RjirfLeyz
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Installing the tools
        run: dotnet tool install --global dotnet-ef

      - name: Restore backend dependencies
        run: dotnet restore

      - name: Build backend
        run: dotnet build --no-restore

      - name: Update database
        run: dotnet ef database update -c Money.Data.ApplicationDbContext --project Money.Api

      - name: Test
        run: dotnet test --no-build --verbosity normal
